name: phishpop
description: "A comprehensive mobile security app that detects and analyzes phishing threats, malicious URLs, suspicious messages, and unsafe QR codes. Family-focused protection with educational scam library and emergency contacts."
publish_to: 'none'
version: 1.0.2+6

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.9.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.10.0
  google_fonts: ^6.3.1
  image_picker: ^1.2.0
  intl: ^0.19.0
  mobile_scanner: ^7.0.1
  path: ^1.8.3
  provider: ^6.1.5+1
  shared_preferences: ^2.3.2
  sqflite: ^2.3.0
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.2
  purchases_flutter: ^8.3.0
  receive_sharing_intent: ^1.8.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  faker: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
