// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC221xk5BirdP-Ecfbad0jGfQ3Q7qqlEmM',
    appId: '1:803080174735:android:61c59951d0871c131d44fa',
    messagingSenderId: '803080174735',
    projectId: 'phishpop-app',
    storageBucket: 'phishpop-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbkmus_AI3m8PrKMflfSQIy0IzjN1diM',
    appId: '1:803080174735:ios:7965e9c8e4fd2f721d44fa',
    messagingSenderId: '803080174735',
    projectId: 'phishpop-app',
    storageBucket: 'phishpop-app.firebasestorage.app',
    androidClientId:
        '803080174735-gesh3072t1jlhhn7titi5nhtfok6ektt.apps.googleusercontent.com',
    iosClientId:
        '803080174735-3q7abft9eduqinuk57qtp066dlnki6ui.apps.googleusercontent.com',
    iosBundleId: 'com.andressaumet.phishpop',
  );
}
